#ifndef GUARD_CONSTANTS_HOENN_MAP_STUBS_H
#define GUARD_CONSTANTS_HOENN_MAP_STUBS_H

/*
 * Hoenn indoor map stubs.
 * These maps are referenced by Hoenn outdoor maps but not yet implemented.
 * All point to MAP_UNDEFINED to allow the ROM to compile.
 * Replace with real map IDs when Hoenn indoor maps are implemented.
 */

#define MAP_ANCIENT_TOMB                                       MAP_UNDEFINED
#define MAP_AQUA_HIDEOUT_1F                                    MAP_UNDEFINED
#define MAP_DESERT_RUINS                                       MAP_UNDEFINED
#define MAP_DEWFORD_TOWN_GYM                                   MAP_UNDEFINED
#define MAP_DEWFORD_TOWN_HALL                                  MAP_UNDEFINED
#define MAP_DEWFORD_TOWN_HOUSE1                                MAP_UNDEFINED
#define MAP_DEWFORD_TOWN_HOUSE2                                MAP_UNDEFINED
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F                     MAP_UNDEFINED
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F                 MAP_UNDEFINED
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F                 MAP_UNDEFINED
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY                   MAP_UNDEFINED
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE                        MAP_UNDEFINED
#define MAP_FALLARBOR_TOWN_MART                                MAP_UNDEFINED
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE               MAP_UNDEFINED
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F                   MAP_UNDEFINED
#define MAP_FORTREE_CITY_DECORATION_SHOP                       MAP_UNDEFINED
#define MAP_FORTREE_CITY_GYM                                   MAP_UNDEFINED
#define MAP_FORTREE_CITY_HOUSE1                                MAP_UNDEFINED
#define MAP_FORTREE_CITY_HOUSE2                                MAP_UNDEFINED
#define MAP_FORTREE_CITY_HOUSE3                                MAP_UNDEFINED
#define MAP_FORTREE_CITY_HOUSE4                                MAP_UNDEFINED
#define MAP_FORTREE_CITY_HOUSE5                                MAP_UNDEFINED
#define MAP_FORTREE_CITY_MART                                  MAP_UNDEFINED
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F                     MAP_UNDEFINED
#define MAP_LAVARIDGE_TOWN_GYM_1F                              MAP_UNDEFINED
#define MAP_LAVARIDGE_TOWN_HERB_SHOP                           MAP_UNDEFINED
#define MAP_LAVARIDGE_TOWN_HOUSE                               MAP_UNDEFINED
#define MAP_LAVARIDGE_TOWN_MART                                MAP_UNDEFINED
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F                   MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY                        MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F                   MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F                  MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_HARBOR                               MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_HOUSE1                               MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_HOUSE2                               MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_HOUSE3                               MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_HOUSE4                               MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F                   MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE                  MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F                    MAP_UNDEFINED
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB             MAP_UNDEFINED
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F                  MAP_UNDEFINED
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F                      MAP_UNDEFINED
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB               MAP_UNDEFINED
#define MAP_MAGMA_HIDEOUT_1F                                   MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_BIKE_SHOP                            MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_GAME_CORNER                          MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_GYM                                  MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_HOUSE1                               MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_HOUSE2                               MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_MART                                 MAP_UNDEFINED
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F                    MAP_UNDEFINED
#define MAP_MIRAGE_TOWER_1F                                    MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F                       MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_GYM                                  MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_HOUSE1                               MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_HOUSE2                               MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_HOUSE3                               MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_HOUSE4                               MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_MART                                 MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F                    MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F                      MAP_UNDEFINED
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE                        MAP_UNDEFINED
#define MAP_NEW_MAUVILLE_ENTRANCE                              MAP_UNDEFINED
#define MAP_OLDALE_TOWN_HOUSE1                                 MAP_UNDEFINED
#define MAP_OLDALE_TOWN_HOUSE2                                 MAP_UNDEFINED
#define MAP_OLDALE_TOWN_MART                                   MAP_UNDEFINED
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F                      MAP_UNDEFINED
#define MAP_PACIFIDLOG_TOWN_HOUSE1                             MAP_UNDEFINED
#define MAP_PACIFIDLOG_TOWN_HOUSE2                             MAP_UNDEFINED
#define MAP_PACIFIDLOG_TOWN_HOUSE3                             MAP_UNDEFINED
#define MAP_PACIFIDLOG_TOWN_HOUSE4                             MAP_UNDEFINED
#define MAP_PACIFIDLOG_TOWN_HOUSE5                             MAP_UNDEFINED
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F                  MAP_UNDEFINED
#define MAP_PETALBURG_CITY_GYM                                 MAP_UNDEFINED
#define MAP_PETALBURG_CITY_HOUSE1                              MAP_UNDEFINED
#define MAP_PETALBURG_CITY_HOUSE2                              MAP_UNDEFINED
#define MAP_PETALBURG_CITY_MART                                MAP_UNDEFINED
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F                   MAP_UNDEFINED
#define MAP_PETALBURG_CITY_WALLYS_HOUSE                        MAP_UNDEFINED
#define MAP_ROUTE104_MR_BRINEYS_HOUSE                          MAP_UNDEFINED
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP                  MAP_UNDEFINED
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE       MAP_UNDEFINED
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE       MAP_UNDEFINED
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                      MAP_UNDEFINED
#define MAP_ROUTE111_OLD_LADYS_REST_STOP                       MAP_UNDEFINED
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE                   MAP_UNDEFINED
#define MAP_ROUTE112_CABLE_CAR_STATION                         MAP_UNDEFINED
#define MAP_ROUTE113_GLASS_WORKSHOP                            MAP_UNDEFINED
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE                      MAP_UNDEFINED
#define MAP_ROUTE114_LANETTES_HOUSE                            MAP_UNDEFINED
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE                      MAP_UNDEFINED
#define MAP_ROUTE119_HOUSE                                     MAP_UNDEFINED
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F                      MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE                        MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F                        MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_FLAT1_1F                             MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_FLAT2_1F                             MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_GYM                                  MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_HOUSE1                               MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_HOUSE2                               MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_HOUSE3                               MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_MART                                 MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F                    MAP_UNDEFINED
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL                       MAP_UNDEFINED
#define MAP_SCENE_CERULEAN_CITY_RIVAL                          MAP_UNDEFINED
#define MAP_SCENE_CERULEAN_CITY_ROCKET                         MAP_UNDEFINED
#define MAP_SCENE_ICEFALL_CAVE_BACK                            MAP_UNDEFINED
#define MAP_SCENE_MT_EMBER_EXTERIOR                            MAP_UNDEFINED
#define MAP_SCENE_MT_MOON_B2F                                  MAP_UNDEFINED
#define MAP_SCENE_ONE_ISLAND_POKEMON_CENTER_1F                 MAP_UNDEFINED
#define MAP_SCENE_PALLET_TOWN_OAK                              MAP_UNDEFINED
#define MAP_SCENE_PALLET_TOWN_PROFESSOR_OAKS_LAB               MAP_UNDEFINED
#define MAP_SCENE_PEWTER_CITY                                  MAP_UNDEFINED
#define MAP_SCENE_PEWTER_CITY_MUSEUM_1F                        MAP_UNDEFINED
#define MAP_SCENE_POKEMON_TOWER_2F                             MAP_UNDEFINED
#define MAP_SCENE_POKEMON_TOWER_6F                             MAP_UNDEFINED
#define MAP_SCENE_ROCKET_WAREHOUSE                             MAP_UNDEFINED
#define MAP_SCENE_ROUTE16                                      MAP_UNDEFINED
#define MAP_SCENE_ROUTE22                                      MAP_UNDEFINED
#define MAP_SCENE_ROUTE23                                      MAP_UNDEFINED
#define MAP_SCENE_ROUTE24                                      MAP_UNDEFINED
#define MAP_SCENE_ROUTE5_ROUTE6_ROUTE7_ROUTE8_GATES            MAP_UNDEFINED
#define MAP_SCENE_SAFFRON_CITY_DOJO                            MAP_UNDEFINED
#define MAP_SCENE_SEAFOAM_ISLANDS_B4F                          MAP_UNDEFINED
#define MAP_SCENE_SILPH_CO_11F                                 MAP_UNDEFINED
#define MAP_SCENE_SILPH_CO_7F                                  MAP_UNDEFINED
#define MAP_SCENE_S_S_ANNE_2F_CORRIDOR                         MAP_UNDEFINED
#define MAP_SCENE_THREE_ISLAND                                 MAP_UNDEFINED
#define MAP_SCENE_TRAINER_TOWER                                MAP_UNDEFINED
#define MAP_SCENE_VICTORY_ROAD_1F                              MAP_UNDEFINED
#define MAP_SCENE_VICTORY_ROAD_2F_BOULDER1                     MAP_UNDEFINED
#define MAP_SCENE_VICTORY_ROAD_2F_BOULDER2                     MAP_UNDEFINED
#define MAP_SCENE_VICTORY_ROAD_3F                              MAP_UNDEFINED
#define MAP_SCENE_VIRIDIAN_CITY_GYM_DOOR                       MAP_UNDEFINED
#define MAP_SCENE_VIRIDIAN_CITY_OLD_MAN                        MAP_UNDEFINED
#define MAP_SCORCHED_SLAB                                      MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY                   MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_HARBOR                              MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_HOUSE                               MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_MART                                MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE                   MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F                   MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F                   MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB                    MAP_UNDEFINED
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F                  MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_GYM_1F                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE1                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE2                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE3                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE4                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE5                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE6                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_HOUSE7                             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE             MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_MART                               MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F            MAP_UNDEFINED
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F                  MAP_UNDEFINED
#define MAP_TERRA_CAVE_ENTRANCE                                MAP_UNDEFINED
#define MAP_TRAINER_HILL_ENTRANCE                              MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE105                                MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE124                                MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE125                                MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE126                                MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE127                                MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE128                                MAP_UNDEFINED
#define MAP_UNDERWATER_ROUTE129                                MAP_UNDEFINED
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY                  MAP_UNDEFINED
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE            MAP_UNDEFINED
#define MAP_VERDANTURF_TOWN_HOUSE                              MAP_UNDEFINED
#define MAP_VERDANTURF_TOWN_MART                               MAP_UNDEFINED
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F                  MAP_UNDEFINED
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE                       MAP_UNDEFINED

#endif /* GUARD_CONSTANTS_HOENN_MAP_STUBS_H */
